Metrics/AbcSize:
  Max: 26

Metrics/BlockLength:
  Max: 28

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  Max: 279

Metrics/MethodLength:
  Max: 20

Layout/LineLength:
  Max: 269

Naming/AccessorMethodName:
  Exclude:
    - 'shorty_app.rb'

Style/Documentation:
  Exclude:
    - 'test/**/*'

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true