version: '2'

services:
  memcached:
    image: memcached
    restart: always

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: em-shorty

  em_shorty:
    depends_on:
      - db
      - memcached
    image: em-shorty
    ports:
      - "8082:8080"
    restart: always
    environment:
      MEMCACHED_URI: memcached:11211
      MYSQL_URI: mysql://root:root@db:3306/em-shorty

volumes:
    db_data:
