development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: em_mysql2
  database: em_shorty
  encoding: utf8
  pool: 100
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock