development:
  adapter: em_mysql2
  database: em_shorty
  encoding: utf8
  pool: 25
  username: root
  password: root
  socket: /run/mysqld/mysqld.sock
  reconnect: true
production:
  adapter: em_mysql2
  host: <%= URI.parse(ENV['MYSQL_URI']).host %>
  port: <%= URI.parse(ENV['MYSQL_URI']).port %>
  database: <%= URI.parse(ENV['MYSQL_URI']).path.split("/").last %>
  encoding: utf8
  pool: 25
  username: <%= URI.parse(ENV['MYSQL_URI']).user %>
  password: <%= URI.parse(ENV['MYSQL_URI']).password %>
  sslca: <%= ENV['MYSQL_SSLCA'] %>
  sslkey: <%= ENV['MYSQL_SSLKEY'] %>
  sslcert: <%= ENV['MYSQL_SSLCERT'] %>
  reconnect: true
test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
