development:
  adapter: mysql2
  database: em_shorty
  encoding: utf8
  pool: 100
  username: root
  password: root
  socket: true

production:
  adapter: mysql2
  database: em_shorty
  encoding: utf8
  pool: 100
  username: root
  password: root
  socket: true

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
